[versions]
# Build & Kotlin
agp = "9.0.1"
kotlin = "2.3.10"
ksp = "2.3.5"

# Core Libraries
core-ktx = "1.17.0"
datastore = "1.2.0"
room = "2.8.4"

# Compose Libraries
compose-ui = "1.10.3"
material3 = "1.4.0"
material-icons = "1.7.8"
activity-compose = "1.12.4"
navigation-compose = "2.9.7"
accompanist = "0.37.3"

# Hilt
hilt = "2.59.1"
hilt-navigation = "1.3.0"

# Serialization
serialization-csv = "0.0.23"

[plugins]
# Build & Kotlin Plugins
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
google-devtools = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[libraries]
# Xposed
xposed-api = { group = "de.robv.android.xposed", name = "api", version = "82" }

# Core Libraries
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

# Compose Libraries
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose-ui" }
compose-animation = { group = "androidx.compose.animation", name = "animation", version.ref = "compose-ui" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "material-icons" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }
accompanist-drawablepainter = { group = "com.google.accompanist", name = "accompanist-drawablepainter", version.ref = "accompanist" }

# Hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-navigation" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }

# Serialization
kotlinx-serialization-csv = { group = "app.softwork", name = "kotlinx-serialization-csv", version.ref = "serialization-csv" }
